name: Labeling new issue
on:
  issues:
    types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.PDF_ISSUE_TOKEN }}
          labels-synonyms: '{"CSS":["SASS","LESS","Bootstrap", "Tailwind", "Material UI", "Chakra UI"],"JavaScript":["TypeScript", "React", "ReactJS", "VueJS", "Angular", "Svelte"], "C#":["CSharp", "C Sharp", "C-Sharp"], "MongoDB":["Mongo", "Mongo DB"]}'
          labels-not-allowed: '["Falta de informações"]'
          default-labels: '["PDF"]'